### ISSUE TITLE
Archive failed with CoreData objects extension

### ISSUE THREAD

**Issue by andr3a88-amk** [unsignedapps/swift-create-xcframework#97]
Hi,

Running `swift create-xcframework --platform ios` in my project that use CoreData objects I receive this error:

````
/...../MetricEntity.swift:10:11: error: cannot find type 'MetricEntity' in scope
extension DiagnosticMetricEntity {
          ^~~~~~~~~~~~~~~~~~~~~~


** ARCHIVE FAILED **
````

The corresponding file is the following:

```
import CoreData

extension MetricEntity {
    convenience init(metric: MetricEntity, insertInto context: NSManagedObjectContext) {
        self.init(context: context)
    }
}
```

**If I comment the extensions `MetricEntity` the archive is correctly created**. 

I think that in some way the tool can't recognize the MetricEntity class inside the Core data model (xcdatamodeld). 

Does anyone have any suggestions for solving this?

### Env 

**swift-create-xcframework version:** latest version that works with Swift 5.0
**Swift version:** `swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)`
**Environment:** Xcode 15.1, Mac OS Sonoma 14.2.1 (23C71)

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

Run `swift create-xcframework --platform ios`

### Expected behavior

The archive should be created with success

**Comment by andr3a88-amk** [comment]
The problem is that the tool is not copying the `Model.xcdatamodeld` in the generated Xcode Project.
