### ISSUE TITLE
Unable to build with target arm64-apple-darwin22.1.0

### ISSUE THREAD

**Issue by Erwangf** [unsignedapps/swift-create-xcframework#87]
I cannot build create-xcframework with the command `sudo make install` on my Mac, for target : `arm64-apple-darwin22.1.0`. 

**My swift-create-xcframework version** : master
**My Swift version:** Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51) Target: arm64-apple-darwin22.1.0
**My Environment:** Xcode 14.2, MacOS 13.0 (22A380)

➡️ My colleague can build without error, and also has a M1 MacBook, but with the following swift --version : 

```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```

**His swift-create-xcframework version** : master
**His Environment:** Xcode 14.2, MacOS 13.0.1 (22A400)

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/unsignedapps/swift-create-xcframework/issues)

### Steps to Reproduce

Run the following command : 

`make install`

### Expected behavior

It should install swift-create-xcframework.

### Actual behavior

```
swift build  --configuration release
error: 'swift-create-xcframework': Invalid manifest
/Users/erwan/Documents/dev/swift-create-xcframework/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
make: *** [build-release] Error 1
```

**Comment by mosamer** [comment]
I had a similar issue due mis-setup of Xcode command line tools. 

To confirm this is your case, may be run `xcodebuild -version` if it didn't work (produced an error) then you need to setup command line tools using
```sudo xcode-select -s /Application/Xcode.app/Contents/Developer```

Hope this helps :)

**Comment by Erwangf** [comment]
Hello,
When I run `xcodebuild -version` I get the following prompt : 
```
Xcode 14.2
Build version 14C18
```
